services:
  test:
    image: maven:3.9.11-eclipse-temurin-21

    working_dir: /src

    volumes:
      - type: bind
        source: .
        target: /src
        read_only: true

    entrypoint: ["mvn", "-Ptest", "clean", "verify", "-Dspring.profiles.active=test", "--no-transfer-progress"]

    container_name: test

    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SERVER_PORT=8080

    restart: no

    depends_on:
      mailhog:
        condition: service_started

    networks:
      - test-network

  mailhog:
    image: mailhog/mailhog:latest

    container_name: test-mailhog

    ports:
      - "1025:1025"
      - "8025:8025"

    restart: no

    networks:
      - test-network

networks:
  test-network:
    driver: bridge
