apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mailhog
  labels:
    app: mailhog
spec:
  serviceName: mailhog
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
      - name: mailhog
        image: mailhog/mailhog:latest
        ports:
        - containerPort: 1025
          name: smtp
        - containerPort: 8025
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog
  labels:
    app: mailhog
spec:
  selector:
    app: mailhog
  ports:
  - port: 1025
    targetPort: 1025
    name: smtp
  - port: 8025
    targetPort: 8025
    name: http
  clusterIP: None
